#!/usr/bin/env node
/**
 * Compiles content/posts/*.md into src/generated/posts.ts.
 *
 * Frontmatter parsing and Markdown rendering happen HERE, at build time, in
 * Node — not in the Worker. That keeps `gray-matter` and `marked` out of the
 * deployed bundle, keeps cold starts fast, and means a malformed post fails the
 * build instead of a request.
 *
 * Run it via `npm run content:build` (dev/deploy/test do this automatically).
 */

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, basename, extname } from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";
import { marked } from "marked";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const POSTS_DIR = join(ROOT, "content", "posts");
const OUT_DIR = join(ROOT, "src", "generated");
const OUT_FILE = join(OUT_DIR, "posts.ts");

marked.setOptions({ gfm: true, breaks: false });

/** Turn a filename into a URL slug: "2026-01-02-my-post.md" -> "my-post". */
function slugFromFilename(filename) {
  const base = basename(filename, extname(filename));
  // Strip a leading ISO date prefix if the file uses the dated convention.
  return base.replace(/^\d{4}-\d{2}-\d{2}-/, "");
}

/** Strip Markdown/HTML down to plain text for excerpts and read-time. */
function toPlainText(markdown) {
  return markdown
    .replace(/```[\s\S]*?```/g, " ") // fenced code
    .replace(/`[^`]*`/g, " ") // inline code
    .replace(/!\[[^\]]*\]\([^)]*\)/g, " ") // images
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1") // links -> text
    .replace(/^[#>\-*+]\s+/gm, "") // list/heading/quote markers
    .replace(/[*_~]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function excerptFrom(plain, limit = 200) {
  if (plain.length <= limit) return plain;
  const cut = plain.slice(0, limit);
  const lastSpace = cut.lastIndexOf(" ");
  return `${(lastSpace > 80 ? cut.slice(0, lastSpace) : cut).trimEnd()}…`;
}

function fail(file, message) {
  throw new Error(`[content] ${file}: ${message}`);
}

function normalizeDate(value, file) {
  if (value instanceof Date) return value.toISOString();
  if (typeof value === "string") {
    const parsed = new Date(value);
    if (Number.isNaN(parsed.getTime())) fail(file, `unparseable date "${value}"`);
    return parsed.toISOString();
  }
  fail(file, "frontmatter is missing required `date`");
}

async function main() {
  let filenames;
  try {
    filenames = (await readdir(POSTS_DIR)).filter((f) => f.endsWith(".md"));
  } catch (err) {
    if (err.code === "ENOENT") fail("content/posts", "directory does not exist");
    throw err;
  }
  filenames.sort();

  const posts = [];
  const seenSlugs = new Map();

  for (const filename of filenames) {
    const raw = await readFile(join(POSTS_DIR, filename), "utf8");
    const { data, content } = matter(raw);

    if (!data.title) fail(filename, "frontmatter is missing required `title`");

    const slug = data.slug ? String(data.slug) : slugFromFilename(filename);
    if (seenSlugs.has(slug)) {
      fail(filename, `slug "${slug}" already used by ${seenSlugs.get(slug)}`);
    }
    seenSlugs.set(slug, filename);

    const plain = toPlainText(content);
    const words = plain ? plain.split(" ").length : 0;

    posts.push({
      slug,
      title: String(data.title),
      date: normalizeDate(data.date, filename),
      updated: data.updated ? normalizeDate(data.updated, filename) : null,
      // A post is published unless it explicitly says `draft: true`.
      draft: data.draft === true,
      tags: Array.isArray(data.tags) ? data.tags.map(String) : [],
      author: data.author ? String(data.author) : null,
      excerpt: data.excerpt ? String(data.excerpt) : excerptFrom(plain),
      readingMinutes: Math.max(1, Math.round(words / 220)),
      markdown: content.trim(),
      html: marked.parse(content).trim(),
      sourceFile: `content/posts/${filename}`,
    });
  }

  // Newest first — the order the API serves them in.
  posts.sort((a, b) => b.date.localeCompare(a.date));

  const banner =
    "// AUTO-GENERATED by scripts/build-content.mjs — do not edit.\n" +
    "// Regenerate with: npm run content:build\n\n" +
    'import type { Post } from "../types";\n\n';

  const body = `export const POSTS: readonly Post[] = ${JSON.stringify(posts, null, 2)} as const;\n`;

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(OUT_FILE, banner + body, "utf8");

  const drafts = posts.filter((p) => p.draft).length;
  console.log(
    `[content] ${posts.length} post(s) compiled` +
      (drafts ? ` (${drafts} draft${drafts === 1 ? "" : "s"})` : "") +
      ` -> src/generated/posts.ts`,
  );
}

main().catch((err) => {
  console.error(err.message ?? err);
  process.exit(1);
});
